#!/bin/bash

cd /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution
tmpDir=$(mkdir -p "/home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/tmp.e32c272f" && echo "/home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/tmp.e32c272f")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution

)
out95f53508="${tmpDir}/out.$$" err95f53508="${tmpDir}/err.$$"
mkfifo "$out95f53508" "$err95f53508"
trap 'rm "$out95f53508" "$err95f53508"' EXIT
tee '/home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution/stdout' < "$out95f53508" &
tee '/home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution/stderr' < "$err95f53508" >&2 &
(
cd /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution


whereis samtools
whereis bwa
)  > "$out95f53508" 2> "$err95f53508"
echo $? > /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution
sync


)
mv /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution/rc.tmp /home/ubuntu/repos/bwa/cromwell-executions/test_location/95f53508-2a13-4e87-976c-218d1d5dfcb4/call-find_tools/execution/rc
