#!/bin/bash

cd /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution
tmpDir=$(mkdir -p "/cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/tmp.3fdbd1fd" && echo "/cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/tmp.3fdbd1fd")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution

)
out9c715172="${tmpDir}/out.$$" err9c715172="${tmpDir}/err.$$"
mkfifo "$out9c715172" "$err9c715172"
trap 'rm "$out9c715172" "$err9c715172"' EXIT
tee '/cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution/stdout' < "$out9c715172" &
tee '/cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution/stderr' < "$err9c715172" >&2 &
(
cd /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution


whereis samtools
whereis bwa
)  > "$out9c715172" 2> "$err9c715172"
echo $? > /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution
sync


)
mv /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution/rc.tmp /cromwell-executions/test_location/9c715172-5b33-4112-871d-a4383d421b2c/call-find_tools/execution/rc
