#!/bin/bash

cd /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/tmp.aac82f90" && echo "/cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/tmp.aac82f90")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution

)
out08f1a3ac="${tmpDir}/out.$$" err08f1a3ac="${tmpDir}/err.$$"
mkfifo "$out08f1a3ac" "$err08f1a3ac"
trap 'rm "$out08f1a3ac" "$err08f1a3ac"' EXIT
tee '/cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution/stdout' < "$out08f1a3ac" &
tee '/cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution/stderr' < "$err08f1a3ac" >&2 &
(
cd /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution


set -euo pipefail
mkdir -p tmp/
bwa mem -M \
    -t 8   \
    -R  '@RG\tID:121005_h804_0096_AD0V4NACXX-NoIndex_6\tLB:PCSI0022C\tPL:ILLUMINA\tPU:121005_h804_0096_AD0V4NACXX-NoIndex_6\tSM:PCSI0022C' \
    /home/ubuntu/Downloads/sample_data/hg19_random.fa \
    /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/inputs/-1809167059/PCSI0022C.val.1.fastq.gz \
    /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/inputs/-1809167059/PCSI0022C.val.2.fastq.gz \
| \
samtools sort -O bam -T tmp/ -o PCSI0022C.val.1.fastq.gz.bam -
)  > "$out08f1a3ac" 2> "$err08f1a3ac"
echo $? > /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution
sync


)
mv /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution/rc.tmp /cromwell-executions/bwaMem/08f1a3ac-9203-40f3-9f98-874678587d7f/call-runBwaMem/shard-0/execution/rc
